"""empty message

Revision ID: e59e6b95cb10
Revises: 5d2a26a9aa62
Create Date: 2022-08-02 00:12:41.795523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59e6b95cb10'
down_revision = '5d2a26a9aa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('users', 'passoword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passoword', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
